In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial import distance_matrix
from numpy.random import seed
from numpy.random import randint
from math import sqrt
import string
import sys

### Read CSV
##### Input: filename

In [7]:

def read_file(name):
    df = pd.read_csv('../data/'+name);
    # node names array
    namesArr = df.columns.values
#     print("**** Node names array ****\n",namesArr)

    # nodes dictionary
    dict = {}
    for i in range(0, df.columns.size):
        dict[df.columns[i]] = i;
#     print("\n**** Nodes dictionary ****")
#     for x in dict:
#       print(x,"-", dict[x])  

    # distances matrix
#     print('\n'.join(df.to_string(index = False).split('\n')[1:]))
    return namesArr, dict, df.values

### Generate n nodes
##### Input: n (number of nodes), lim - space limit

In [8]:
def generate_n_nodes(n,lim):
    # Nodes position (x,y)
    seed(1)
    coord = []
    xList = []
    yList = []
    for i in range(0, n):
        x = randint(0, lim)
        xList.append(x)
        y = randint(0, lim)
        yList.append(y)
        coord.append((x,y))
    mx = float('-inf')
    for x,y in coord:
        if x > mx:
            mx = x
        if y > mx:
            mx = y
    # Nodes Dictionary
    dict = {}
#     print("\n**** Nodes dictionary ****")
#     plt.plot(xList,yList,zorder=1) 
#     plt.scatter(xList,yList,zorder=2)
    alphabet_string = string.ascii_uppercase
    alphabet_list = list(alphabet_string)
    alphabet_list = alphabet_list[:n]
    for i, txt in enumerate(alphabet_list):
        dict[txt] = i;
#         plt.annotate(txt, (xList[i]+.25, yList[i]), fontsize=12)

#     Distances matrix 
    # d=√((x_2-x_1)²+(y_2-y_1)²)
    tempList = []
    for x,y in coord:
        for i,j in coord :
            tempList.append(round(sqrt(pow((x-i),2) + pow((y-j),2) ),1))
    mat = []
    while tempList != []:
      mat.append(tempList[:n])
      tempList = tempList[n:]
    dist_mat = pd.DataFrame(mat)
    return coord, dict, dist_mat


### Objective Function
##### Input: nodes names array, nodes dictionary, distances matrix, individual array

In [9]:
def objective_function(namesArr,d, dMatrix, sol):
    if sol[0] != sol[len(sol)-1]: return -1 #the fist and last character must be the same
    rep = sol.rstrip(sol[-1])
    if not len(set(rep)) == len(rep): return -1 # the nodes aren't repeated
    if sorted(rep) != sorted(namesArr): return -1 # all the nodes are included in the solution
    
    n = len(namesArr)
    w = 0;
    for i in range(0, n):
            w+=dMatrix[ord(sol[i])-65][ord(sol[i+1])-65]
    return w
 

In [10]:
# MAIN
print("\n--------------------------------- 1. Read the source file ------------------------------------------------")
print("\t~~~~ Nodes names array ~~~~ ")
print(read_file("adjacency_matrix.csv")[0])
print("\t~~~~ Nodes dictionary ~~~~ ")
print(read_file("adjacency_matrix.csv")[1])
print("\~~~~ Distances Matrix ~~~~ ")
print(read_file("adjacency_matrix.csv")[2])
print("\n--------------------------------- 2. Generate n nodes ------------------------------------------------")
print("\t~~~~ Nodes position (x,y) ~~~~ ")
n = int(input("-> # nodes: "))
lim = int(input("-> lim: "))
print(generate_n_nodes(n,lim)[0] )
print("\t~~~~ Nodes dictionary ~~~~ ")
print(generate_n_nodes(n,lim)[1] )
print("\t~~~~ Distances Matrix ~~~~ ")
print(generate_n_nodes(n,lim)[2] )
print("\n--------------------------------- 3. Objective function ------------------------------------------------")
namesArr = read_file("adjacency_matrix.csv")[0]
dictionary = read_file("adjacency_matrix.csv")[1]
matrix = read_file("adjacency_matrix.csv")[2]
print("weight: ",objective_function(namesArr, dictionary, matrix, input("solution: ")))



--------------------------------- 1. Read the source file ------------------------------------------------
	~~~~ Nodes names array ~~~~ 
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
	~~~~ Nodes dictionary ~~~~ 
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9}
\~~~~ Distances Matrix ~~~~ 
[[ 0 59 48 69 54 91 55 34 81 72]
 [59  0 45 19 45 73 48 13 13 42]
 [48 45  0 97 11 65 12 58 70 45]
 [69 19 97  0 31 94 23 66 71 13]
 [54 45 11 31  0 95 37 47 24 49]
 [91 73 65 94 95  0 62 35 38 61]
 [55 48 12 23 37 62  0 82 96 47]
 [34 13 58 66 47 35 82  0 10 47]
 [81 13 70 71 24 38 96 10  0 63]
 [72 42 45 13 49 61 47 47 63  0]]

--------------------------------- 2. Generate n nodes ------------------------------------------------
	~~~~ Nodes position (x,y) ~~~~ 
-> # nodes: 10
-> lim: 100
[(37, 12), (72, 9), (75, 5), (79, 64), (16, 1), (76, 71), (6, 25), (50, 20), (18, 84), (11, 28)]
	~~~~ Nodes dictionary ~~~~ 
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H'