In [43]:
import pandas as pd
import numpy as np

## 1. Read CSV

In [77]:
df = pd.read_csv('example1.csv', header=None)
matrix = df.to_numpy()
d=[]
x = 0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if(matrix[i,j] > 0):
            d.append( [[i,j],matrix[i,j]])
            x+=1
print(matrix)

[[0 0 6 0 0 0 5 0 7]
 [0 9 0 0 6 8 0 0 0]
 [7 0 8 0 0 5 0 0 4]
 [0 0 1 5 0 4 2 9 0]
 [0 7 0 0 3 0 0 0 0]
 [3 0 9 0 0 0 7 1 0]
 [0 5 0 0 4 0 8 0 9]
 [0 8 2 6 0 0 0 0 0]
 [0 0 0 0 2 7 4 0 6]]


## 2. Generate population

In [84]:
def initial_population(arr):
    # generate random matrix with values from 1->9
    x=-1
    y=-1
    val = -1
    population = np.random.randint(low=1,high=9, size=(9, 9))
    for i in range(len(arr)):
        x = arr[i][0][0]
        y = arr[i][0][1]
        val = arr[i][1]
        population[x,y] = val
        # for j in range(population.shape[1]):
            
    return population
initial_population(d)

array([[5, 1, 6, 5, 6, 4, 5, 1, 7],
       [5, 9, 6, 7, 6, 8, 7, 7, 3],
       [7, 5, 8, 2, 8, 5, 3, 7, 4],
       [2, 2, 1, 5, 2, 4, 2, 9, 4],
       [7, 7, 8, 1, 3, 1, 7, 1, 8],
       [3, 8, 9, 1, 4, 8, 7, 1, 3],
       [1, 5, 2, 3, 4, 2, 8, 1, 9],
       [3, 8, 2, 6, 3, 5, 5, 3, 3],
       [2, 1, 2, 8, 2, 7, 4, 1, 6]])

## 3. Calculate fitness

## 4. Algorithm

## 5. Crossover

## 6. Mutation