In [231]:
import pandas as pd
import numpy as np

## Draw Sudoku

In [232]:
def draw_sudoku(board):
    print("+" + "---+"*9)
    for i, row in enumerate(board):
        print(("|" + " {}   {}   {} |"*3).format(*[x if x != 0 else "0" for x in row]))
        if i % 3 == 2:
            print("+" + "---+"*9)

## Read CSV

In [233]:
df = pd.read_csv('example1.csv', header=None)
matrix = df.to_numpy()
d=[]
x = 0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if(matrix[i,j] > 0):
            d.append( [[i,j],matrix[i,j]])
            x+=1
draw_sudoku(matrix)

+---+---+---+---+---+---+---+---+---+
| 0   0   6 | 0   0   0 | 5   0   7 |
| 0   9   0 | 0   6   8 | 0   0   0 |
| 7   0   8 | 0   0   5 | 0   0   4 |
+---+---+---+---+---+---+---+---+---+
| 0   0   1 | 5   0   4 | 2   9   0 |
| 0   7   0 | 0   3   0 | 0   0   0 |
| 3   0   9 | 0   0   0 | 7   1   0 |
+---+---+---+---+---+---+---+---+---+
| 0   5   0 | 0   4   0 | 8   0   9 |
| 0   8   2 | 6   0   0 | 0   0   0 |
| 0   0   0 | 0   2   7 | 4   0   6 |
+---+---+---+---+---+---+---+---+---+


## Generate population

In [234]:
def initial_population(arr, n):    # generate n random matrix with values from 1->9
    x=y=val=-1
    population = []
    for i in range(n):
        population.append(np.zeros((9,9)))
    for j in range(n):
        mat = np.random.randint(low=1,high=9, size=(9, 9))
        for i in range(len(arr)):
            x = arr[i][0][0]
            y = arr[i][0][1]
            val = arr[i][1]
            mat[x,y] = val
        population[j] = mat
    return population

## Calculate fitness

## Algorithm

## Crossover

In [290]:
def tournament_selection(parents,fitness,population):
    popsize = len(population)
    i1, i2 = np.random.choice(popsize,2)
    if fitness[i1] <= fitness[i2]:
        return population[i1]
    else:
        return population[i2]

In [306]:
def crossover(first, second):
    print("crossover")

    return first #change this

In [307]:
def crossover_parents(population, pr):
    # n = np.random.randint(low=0,high=8)
    gen = np.zeros_like(population)
    fitness = [0,98,0,2,100]
    for i in range(len(population)):
        if(np.random.uniform(0, 1) < pr):
            # print("select two")
            first = tournament_selection(population, fitness, population)
            second = tournament_selection(population, fitness, population)
            child = crossover(first,second)
            gen[i,:] = np.copy(child)
        else:
            # print("clone")
            parent = tournament_selection(population, fitness, population)
            gen[i,:] = np.copy(parent)
    print(gen)
crossover_parents(population, pr)

crossover
[[[4 3 6 1 4 4 5 3 7]
  [8 9 5 3 6 8 1 2 1]
  [7 3 8 2 2 5 8 3 4]
  [5 5 1 5 1 4 2 9 2]
  [3 7 6 6 3 6 7 2 2]
  [3 6 9 4 4 1 7 1 4]
  [1 5 2 6 4 5 8 4 9]
  [3 8 2 6 6 2 4 2 1]
  [2 3 7 2 2 7 4 1 6]]

 [[4 3 6 1 4 4 5 3 7]
  [8 9 5 3 6 8 1 2 1]
  [7 3 8 2 2 5 8 3 4]
  [5 5 1 5 1 4 2 9 2]
  [3 7 6 6 3 6 7 2 2]
  [3 6 9 4 4 1 7 1 4]
  [1 5 2 6 4 5 8 4 9]
  [3 8 2 6 6 2 4 2 1]
  [2 3 7 2 2 7 4 1 6]]

 [[7 1 6 1 6 3 5 8 7]
  [3 9 7 3 6 8 5 8 8]
  [7 1 8 2 6 5 6 1 4]
  [5 3 1 5 4 4 2 9 3]
  [5 7 3 6 3 5 8 7 8]
  [3 7 9 3 2 5 7 1 2]
  [3 5 1 8 4 5 8 6 9]
  [2 8 2 6 2 3 7 2 6]
  [2 8 4 3 2 7 4 3 6]]

 [[2 5 6 5 4 5 5 8 7]
  [3 9 4 1 6 8 6 2 5]
  [7 6 8 2 4 5 6 1 4]
  [1 5 1 5 8 4 2 9 5]
  [7 7 3 7 3 7 7 6 8]
  [3 2 9 4 4 7 7 1 1]
  [5 5 2 3 4 4 8 2 9]
  [6 8 2 6 5 5 4 1 1]
  [1 5 8 5 2 7 4 8 6]]

 [[4 3 6 1 4 4 5 3 7]
  [8 9 5 3 6 8 1 2 1]
  [7 3 8 2 2 5 8 3 4]
  [5 5 1 5 1 4 2 9 2]
  [3 7 6 6 3 6 7 2 2]
  [3 6 9 4 4 1 7 1 4]
  [1 5 2 6 4 5 8 4 9]
  [3 8 2 6 6 2 4 2 1]
  [2 3 7 2 2 7

## Mutation

# Main Code

In [281]:
pr = 0.5
n = 5 # n matrixes solutions

population = initial_population(d,n)

# show initial population
x=1
for i in population:
    print("**************** "+ str(x)+ " SUDOKU " +"****************")
    x+=1
    draw_sudoku(i)

# crossover_parents(population, pr)

**************** 1 SUDOKU ****************
+---+---+---+---+---+---+---+---+---+
| 7   5   6 | 5   7   3 | 5   8   7 |
| 5   9   8 | 3   6   8 | 4   8   8 |
| 7   6   8 | 3   8   5 | 7   1   4 |
+---+---+---+---+---+---+---+---+---+
| 2   3   1 | 5   4   4 | 2   9   3 |
| 7   7   3 | 6   3   6 | 7   5   1 |
| 3   1   9 | 2   4   4 | 7   1   4 |
+---+---+---+---+---+---+---+---+---+
| 1   5   4 | 1   4   6 | 8   7   9 |
| 4   8   2 | 6   5   2 | 8   2   7 |
| 1   8   7 | 2   2   7 | 4   7   6 |
+---+---+---+---+---+---+---+---+---+
**************** 2 SUDOKU ****************
+---+---+---+---+---+---+---+---+---+
| 7   1   6 | 1   6   3 | 5   8   7 |
| 3   9   7 | 3   6   8 | 5   8   8 |
| 7   1   8 | 2   6   5 | 6   1   4 |
+---+---+---+---+---+---+---+---+---+
| 5   3   1 | 5   4   4 | 2   9   3 |
| 5   7   3 | 6   3   5 | 8   7   8 |
| 3   7   9 | 3   2   5 | 7   1   2 |
+---+---+---+---+---+---+---+---+---+
| 3   5   1 | 8   4   5 | 8   6   9 |
| 2   8   2 | 6   2   3 | 7   2   6 |
| 