In [231]:
import pandas as pd
import numpy as np

## Draw Sudoku

In [232]:
def draw_sudoku(board):
    print("+" + "---+"*9)
    for i, row in enumerate(board):
        print(("|" + " {}   {}   {} |"*3).format(*[x if x != 0 else "0" for x in row]))
        if i % 3 == 2:
            print("+" + "---+"*9)

## Read CSV

In [233]:
df = pd.read_csv('example1.csv', header=None)
matrix = df.to_numpy()
d=[]
x = 0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if(matrix[i,j] > 0):
            d.append( [[i,j],matrix[i,j]])
            x+=1
draw_sudoku(matrix)

+---+---+---+---+---+---+---+---+---+
| 0   0   6 | 0   0   0 | 5   0   7 |
| 0   9   0 | 0   6   8 | 0   0   0 |
| 7   0   8 | 0   0   5 | 0   0   4 |
+---+---+---+---+---+---+---+---+---+
| 0   0   1 | 5   0   4 | 2   9   0 |
| 0   7   0 | 0   3   0 | 0   0   0 |
| 3   0   9 | 0   0   0 | 7   1   0 |
+---+---+---+---+---+---+---+---+---+
| 0   5   0 | 0   4   0 | 8   0   9 |
| 0   8   2 | 6   0   0 | 0   0   0 |
| 0   0   0 | 0   2   7 | 4   0   6 |
+---+---+---+---+---+---+---+---+---+


## Generate population

In [234]:
def initial_population(arr, n):    # generate n random matrix with values from 1->9
    x=y=val=-1
    population = []
    for i in range(n):
        population.append(np.zeros((9,9)))
    for j in range(n):
        mat = np.random.randint(low=1,high=9, size=(9, 9))
        for i in range(len(arr)):
            x = arr[i][0][0]
            y = arr[i][0][1]
            val = arr[i][1]
            mat[x,y] = val
        population[j] = mat
    return population

## Calculate fitness

## Algorithm

## Crossover

In [235]:
def tournament_selection(parents, population):
    print("tournament_selection")

In [236]:
def crossover(first, second):
    print("crossover")

In [249]:
def crossover_parents(population, pr):
    # n = np.random.randint(low=0,high=8)
    gen = np.zeros_like(population)
    print(gen)
    for i in range(len(population)):
        if(np.random.uniform(0, 1) < pr):
            # print("select two")
            first = tournament_selection(population, population)
            second = tournament_selection(population, population)
            child = crossover(first,second)
        else:
            # print("clone")
            parent = tournament_selection(population, population)
            # add a copy of the parent in the gen
    # print(n)
crossover_parents(population, pr)

[[[0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0]]



## Mutation

# Main Code

In [247]:
pr = 0.5
n = 10 # n matrixes solutions

population = initial_population(d,n)

# show initial population
x=1
for i in population:
    print("**************** "+ str(x)+ " SUDOKU " +"****************")
    x+=1
    draw_sudoku(i)

# crossover_parents(population, pr)

**************** 1 SUDOKU ****************
+---+---+---+---+---+---+---+---+---+
| 8   1   6 | 7   4   3 | 5   6   7 |
| 1   9   2 | 6   6   8 | 5   3   1 |
| 7   8   8 | 2   5   5 | 4   7   4 |
+---+---+---+---+---+---+---+---+---+
| 7   2   1 | 5   4   4 | 2   9   8 |
| 8   7   5 | 8   3   7 | 4   2   1 |
| 3   6   9 | 2   3   2 | 7   1   4 |
+---+---+---+---+---+---+---+---+---+
| 3   5   2 | 3   4   7 | 8   1   9 |
| 1   8   2 | 6   6   1 | 4   2   8 |
| 3   2   6 | 8   2   7 | 4   3   6 |
+---+---+---+---+---+---+---+---+---+
**************** 2 SUDOKU ****************
+---+---+---+---+---+---+---+---+---+
| 1   7   6 | 4   1   4 | 5   8   7 |
| 7   9   8 | 7   6   8 | 6   8   7 |
| 7   1   8 | 8   3   5 | 7   1   4 |
+---+---+---+---+---+---+---+---+---+
| 6   1   1 | 5   7   4 | 2   9   1 |
| 2   7   4 | 7   3   3 | 1   3   8 |
| 3   7   9 | 7   4   1 | 7   1   7 |
+---+---+---+---+---+---+---+---+---+
| 6   5   5 | 7   4   5 | 8   4   9 |
| 1   8   2 | 6   7   8 | 1   5   8 |
| 

AttributeError: 'list' object has no attribute 'shape'