In [43]:
import pandas as pd
import numpy as np

## 1. Read CSV

In [106]:
df = pd.read_csv('example1.csv', header=None)
matrix = df.to_numpy()
d=[]
x = 0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if(matrix[i,j] > 0):
            d.append( [[i,j],matrix[i,j]])
            x+=1
print(matrix)

[[0 0 6 0 0 0 5 0 7]
 [0 9 0 0 6 8 0 0 0]
 [7 0 8 0 0 5 0 0 4]
 [0 0 1 5 0 4 2 9 0]
 [0 7 0 0 3 0 0 0 0]
 [3 0 9 0 0 0 7 1 0]
 [0 5 0 0 4 0 8 0 9]
 [0 8 2 6 0 0 0 0 0]
 [0 0 0 0 2 7 4 0 6]]


## 2. Generate population

In [110]:
def initial_population(arr):    # generate random matrix with values from 1->9
    x=y=val=-1
    population = np.random.randint(low=1,high=9, size=(9, 9))
    for i in range(len(arr)):
        x = arr[i][0][0]
        y = arr[i][0][1]
        val = arr[i][1]
        population[x,y] = val
    return population
initial_population(d)

array([[1, 2, 6, 3, 6, 5, 5, 8, 7],
       [6, 9, 5, 4, 6, 8, 4, 2, 2],
       [7, 2, 8, 2, 3, 5, 1, 5, 4],
       [5, 5, 1, 5, 1, 4, 2, 9, 5],
       [6, 7, 2, 1, 3, 4, 6, 6, 3],
       [3, 4, 9, 1, 3, 7, 7, 1, 7],
       [6, 5, 6, 6, 4, 2, 8, 4, 9],
       [6, 8, 2, 6, 7, 7, 4, 1, 1],
       [8, 8, 3, 7, 2, 7, 4, 2, 6]])

## 3. Calculate fitness

## 4. Algorithm

## 5. Crossover

## 6. Mutation