In [ ]:
import pandas as pd
import numpy as np

## Draw Sudoku

In [ ]:
def draw_sudoku(board):
    print("+" + "---+"*9)
    for i, row in enumerate(board):
        print(("|" + " {}   {}   {} |"*3).format(*[x if x != 0 else "0" for x in row]))
        if i % 3 == 2:
            print("+" + "---+"*9)

## Read CSV

In [ ]:
df = pd.read_csv('example1.csv', header=None)
matrix = df.to_numpy()
d=[]
x = 0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if(matrix[i,j] > 0):
            d.append( [[i,j],matrix[i,j]])
            x+=1
draw_sudoku(matrix)

# Main Code

In [ ]:
pr = 0.5
n = 5 # n matrixes solutions

population = initial_population(d,n)

# show initial population
x=1
for i in population:
    print("**************** "+ str(x)+ " SUDOKU " +"****************")
    x+=1
    draw_sudoku(i)

# crossover_parents(population, pr)

## Generate population

In [ ]:
def initial_population(arr, n):    # generate n random matrix with values from 1->9
    x=y=val=-1
    population = []
    for i in range(n):
        population.append(np.zeros((9,9)))
    for j in range(n):
        mat = np.random.randint(low=1,high=10, size=(9, 9))
        print(mat)
        for i in range(len(arr)):
            x = arr[i][0][0]
            y = arr[i][0][1]
            val = arr[i][1]
            mat[x,y] = val
        population[j] = mat
    return population

## Calculate fitness

## Algorithm

## Crossover

In [ ]:
def tournament_selection(parents,fitness,population):
    popsize = len(population)
    i1, i2 = np.random.choice(popsize,2)
    if fitness[i1] <= fitness[i2]:
        return population[i1]
    else:
        return population[i2]

In [293]:
def crossover(first, second):
    x = np.random.randint(low=0,high=9)
    offspring = np.zeros((9,9))
    offspring = offspring.astype(int)

    x=4 
    # merge matrixes
    for i in range(x+1):
        for j in range(offspring.shape[0]):
                offspring[i][j] = first[i][j]
    for i in range(x+1, offspring.shape[0]):
        for j in range(offspring.shape[1]):
                offspring[i][j] = second[i][j]
    print(offspring)

    # missing-duplicated
    blocked = []
    for i in range(offspring.shape[0]):
        coords = []
        dupl = {}
        miss = [1,2,3,4,5,6,7,8,9]
        
        for j in range(offspring.shape[1]):
            coords.append([offspring[j,i], [i,j]])
        for j in range(len(coords)):
            rep = np.where(coords == coords[j][0])
            if(rep[0].shape[0] != 1):
                dupl[coords[j][0]] = rep[0]
        for j in range(len(coords)):
            if(coords[j][0] in miss):
                miss.remove(coords[j][0])
        for j in d:
            blocked.append(j[0])
        # print(dupl)
        # print(miss)
        # print(dupl)
        for key, value in dupl.items():
            for z in value:
                if([z,i] in blocked): # si no está en la lista de bloqueados
                    dupl[key] = np.delete(dupl[key],np.where(dupl[key] == z))
        r=1
        for key, value in dupl.items():
                if(r==1):
                    dupl[key] = np.delete(dupl[key],0)
                    r+=1
        for key, value in dupl.items():
            for z in value:
                print([z,i], miss)
                if(len(miss)):
                    offspring[z,i] = miss[0]
                    miss.pop(0)
        print("\n\n")
        # break
    return offspring

mat1 =[[7, 8, 6, 5, 7, 7, 5, 4, 7],
        [8, 9, 4 ,1, 6, 8, 3, 7, 2],
        [7 ,8, 8, 3, 7, 5, 8, 8, 4],
        [3, 4, 1, 5, 2, 4, 2, 9, 7],
        [7, 7, 2, 1, 3, 7, 6, 7, 5],
        [3, 7,9, 5, 2, 1, 7, 1, 3],
        [6, 5, 2, 7, 4, 8, 8, 4, 9],
        [7, 8, 2, 6, 1, 8, 6, 4, 2],
        [8, 3 ,4 ,3 ,2 ,7 ,4 ,7, 6]]

mat2 = [[7, 2, 6, 6, 7, 2 ,5, 5, 7],
        [2, 9, 3, 1, 6, 8, 7, 6, 2],
        [7, 8, 8, 1, 1, 5, 7, 8, 4],
        [3, 3, 1, 5, 6 ,4 ,2, 9, 6],
        [7, 7, 4, 2, 3, 7, 8, 1, 4],
        [3, 8, 9, 6, 5, 1, 7, 1, 7],
        [3, 5, 6, 4, 4, 5 ,8 ,2 ,9],
        [1, 8, 2, 6, 2, 4 ,4 ,3 ,5],
        [6, 1, 2, 6, 2, 7, 4, 1, 6]]
crossover(mat1, mat2)

[[7 8 6 5 7 7 5 4 7]
 [8 9 4 1 6 8 3 7 2]
 [7 8 8 3 7 5 8 8 4]
 [3 4 1 5 2 4 2 9 7]
 [7 7 2 1 3 7 6 7 5]
 [3 8 9 6 5 1 7 1 7]
 [3 5 6 4 4 5 8 2 9]
 [1 8 2 6 2 4 4 3 5]
 [6 1 2 6 2 7 4 1 6]]
[4, 0] [2, 4, 5, 9]
[3, 0] [4, 5, 9]
[6, 0] [5, 9]



[2, 1] [2, 3, 6]
[5, 1] [3, 6]



[4, 2] [3, 5, 7]
[8, 2] [5, 7]



[1, 3] [2, 7, 8, 9]
[4, 3] [7, 8, 9]
[5, 3] [8, 9]
[8, 3] [9]



[2, 4] [1, 8, 9]
[3, 4] [8, 9]
[7, 4] [9]



[4, 5] [2, 3, 6, 9]
[6, 5] [3, 6, 9]
[7, 5] [6, 9]



[7, 6] [1, 9]



[4, 7] [5, 6]
[8, 7] [6]



[5, 8] [1, 3, 8]
[4, 8] [3, 8]
[7, 8] [8]





C:\Users\scago\AppData\Local\Temp\ipykernel_21936\1676155420.py:26: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  rep = np.where(coords == coords[j][0])


array([[7, 8, 6, 5, 7, 7, 5, 4, 7],
       [8, 9, 4, 2, 6, 8, 3, 7, 2],
       [7, 2, 8, 3, 1, 5, 8, 8, 4],
       [4, 4, 1, 5, 8, 4, 2, 9, 7],
       [2, 7, 3, 7, 3, 2, 6, 5, 3],
       [3, 3, 9, 8, 5, 1, 7, 1, 1],
       [5, 5, 6, 4, 4, 3, 8, 2, 9],
       [1, 8, 2, 6, 9, 6, 1, 3, 8],
       [6, 1, 5, 9, 2, 7, 4, 6, 6]])

In [ ]:
def crossover_parents(population, pr):
    # n = np.random.randint(low=0,high=8)
    gen = np.zeros_like(population)
    fitness = [0,98,0,2,100]
    for i in range(len(population)):
        if(np.random.uniform(0, 1) < pr):
            # print("select two")
            first = tournament_selection(population, fitness, population)
            second = tournament_selection(population, fitness, population)
            child = crossover(first,second)
            gen[i,:] = np.copy(child)
        else:
            # print("clone")
            parent = tournament_selection(population, fitness, population)
            gen[i,:] = np.copy(parent)
    # print(gen)
crossover_parents(population, pr)

## Mutation