# **Krilov (polinomio característico)**

In [1]:
import numpy as np

### Input:

In [3]:
mat = np.array([[5,-2,0], [-2,3,-1], [0,-1,1]])
y = np.array([1,0,0])

### Krilov

In [4]:
y = np.ones(3, dtype=int);
size = mat.shape[0] #matrix size
dos = np.ones([3,3],dtype=int)
#dos = np.empty((size,size))
if y.size == 0:
    y=np.ones(size)
dos[0] = y
print("*Matriz original:\n",mat,"\n\n*Vector:\n",y)
for x in range(1,size):
    dos[x]=mat@dos[x-1] #producto escalar
trans = np.transpose(dos)
prod = mat@dos[size-1]
print("\n\nSistema de ecuaciones:\n",trans)
print("\nVector de la ecuación:\n",prod)
x = np.linalg.solve(trans,prod) #resolver sistema de ecuaciones
strr = "m^"+str(size)
print("\n\n\t*Polinomio característico: ")
for z in np.flip(x):
    size-=1
    if(size!=1 and size!=0): strr += " + " + str(-1*int(z)) + "m^" + str(size)
    elif(size==1): strr += " + " + str(-1*int(z)) + "m"
    elif(size==0): strr += " + " + str(-1*int(z))
print("\t\t",strr)

*Matriz original:
 [[ 5 -2  0]
 [-2  3 -1]
 [ 0 -1  1]] 

*Vector:
 [1 1 1]


Sistema de ecuaciones:
 [[ 1  3 15]
 [ 1  0 -6]
 [ 1  0  0]]

Vector de la ecuación:
 [ 87 -48   6]


	*Polinomio característico: 
		 m^3 + -9m^2 + 18m + -6
